// nxmgame.js — n x m quadratic game environment (and its calibration tasks).
//
// Generalizes quadgame.js from scalar actions to x in R^n (human, from the
// 2D-pointer mapping layer) and y in R^m (machine). Same platform contract:
//
//   reset({ P })       -> { P, S, I, O }
//   step({ P, S, I })  -> { Sp, O }
//
// P (all JSON-serializable; matrices are nested arrays):
//   n, m               — dimensions
//   A,B,H,D,C,E        — cost matrices (see nxm_math.js); omit to autogenerate
//   x1,y1,x2,y2        — cost centers (human's / machine's global optima)
//   seed               — autogeneration + initial-condition seed
//   lr                 — machine mode: >0 gradient rate, -1 best response,
//                        0 hold ynash (matches the quadgame convention)
//   K                  — n x m conjecture matrix (0 = myopic); used by both
//                        gradient and best-response modes (Experiment 2)
//   L, l               — affine machine policy y = l + Lx; when set it
//                        overrides lr (Experiment 3 / reverse Stackelberg)
//   ynash              — m-vector for lr == 0
//   taskmode           — 'game' (default) | 'reach' | 'track' | 'hold'
//                        calibration tasks: cost = squared distance to a
//                        fixed / moving / held target (machine disabled)
//   target             — n-vector for reach/hold (autogenerated if absent)
//   amps, freqs        — per-dim sum-of-sines for 'track' (units, Hz)
//   sx, cx             — cost display scale/offset (as in quadgame)
//   x0, y0, random     — initial condition control
//   tol                — start-gate tolerance (used by the experiment layer)
//   fps                — steps per second (for track-mode time base)
//
// S: { t, x (R^n), y (R^m), target (R^n, calibration modes) }
// I: { x (R^n) } — produced by the mapping layer; becomes next S.x directly,
//                  exactly like quadgame's x_next = I.x.
// O: { cost (displayed bar), costH, costM, dNE, dSE, dCC, dMO }
//
// reset() computes the game-theoretic predictions once and stores them in
// P.eq = { NE, SE, CC, MO, K, L } so they are uploaded with every trial's
// params and available to the draw layer and analysis.

import M from './nxm_math.js'

function ensureGame(P) {
    const n = P.n || 2
    const m = P.m || 2
    if (!P.A) {
        const d = M.designGame({ n, m, seed: P.seed || 1 })
        if (!d) throw new Error('nxmgame: designGame failed for n=' + n + ' m=' + m)
        Object.assign(P, {
            A: d.G.A, B: d.G.B, H: d.G.H, D: d.G.D, C: d.G.C, E: d.G.E,
            x1: d.G.x1, y1: d.G.y1, x2: d.G.x2, y2: d.G.y2,
        })
    }
    return M.makeGame({
        A: P.A, B: P.B, H: P.H, D: P.D, C: P.C, E: P.E,
        x1: P.x1, y1: P.y1, x2: P.x2, y2: P.y2,
    })
}

function machineStep({ P, G, x, y }) {
    let yn
    if (P.L && P.l) {
        // committed affine policy (reverse Stackelberg play)
        yn = M.vadd(P.l, M.matvec(P.L, x))
    } else if (P.lr > 0) {
        const g = M.conjecturalGradM(G, K_of(P, G), x, y)
        yn = M.vsub(y, M.vscale(g, P.lr))
    } else if (P.lr === -1) {
        yn = M.conjecturalBRM(G, K_of(P, G), x)
    } else if (P.lr === 0) {
        yn = (P.ynash || M.zeros(G.m)).slice()
    } else {
        console.log('nxmgame: invalid lr ' + P.lr)
        yn = y.slice()
    }
    // probe offset for the outer-loop estimation trials (Experiment 2)
    if (P.yprobe) yn = M.vadd(yn, P.yprobe)
    return M.clipvec(yn, -2, 2)
}

function K_of(P, G) {
    return P.K || M.zeros(G.n, G.m)
}

function trackTarget(P, t) {
    const n = P.n || 2
    const fps = P.fps || 60
    const amps = P.amps || M.zeros(n).map(() => 0.5)
    const freqs = P.freqs || M.zeros(n).map((_, i) => 0.05 + 0.035 * i)
    const phases = P.phases || M.zeros(n).map((_, i) => (i * 2 * Math.PI) / n)
    return M.zeros(n).map((_, i) =>
        amps[i] * Math.sin(2 * Math.PI * freqs[i] * (t / fps) + phases[i]))
}

function costs({ P, S }) {
    const mode = P.taskmode || 'game'
    if (mode === 'game') {
        const G = P._G || ensureGame(P)
        const cH = M.costH(G, S.x, S.y)
        const cM = M.costM(G, S.x, S.y)
        return { costH: cH, costM: cM }
    }
    const target = S.target || M.zeros(P.n || 2)
    const d = M.vsub(S.x, target)
    return { costH: 0.5 * M.dot(d, d), costM: 0, dist: M.norm(d) }
}

function output({ P, S }) {
    const c = costs({ P, S })
    const sx = P.sx == null ? 1 : P.sx
    const cx = P.cx || 0
    const raw = Math.max(sx * c.costH - cx, 0)
    const O = {
        cost: Math.sqrt(raw), // bar height, same sqrt convention as quadgame
        costH: c.costH,
        costM: c.costM,
    }
    if (c.dist != null) O.dist = c.dist
    if (P.eq && (P.taskmode || 'game') === 'game') {
        O.dNE = M.norm(M.vsub(S.x, P.eq.NE.x))
        O.dSE = M.norm(M.vsub(S.x, P.eq.SE.x))
        O.dCC = M.norm(M.vsub(S.x, P.eq.CC.x))
        O.dMO = M.norm(M.vsub(S.x, P.eq.MO.x))
    }
    return { O }
}

function step({ P, S, I }) {
    const n = P.n || 2
    const mode = P.taskmode || 'game'
    // human input becomes the next x (mapping layer already produced R^n)
    const x_next = Array.isArray(I.x) && I.x.length === n
        ? M.clipvec(I.x, -1, 1)
        : S.x.slice()

    let Sp
    if (mode === 'game') {
        const G = P._G || ensureGame(P)
        const y_next = machineStep({ P, G, x: x_next, y: S.y })
        Sp = { t: S.t + 1, x: x_next, y: y_next }
    } else if (mode === 'track') {
        Sp = { t: S.t + 1, x: x_next, y: S.y, target: trackTarget(P, S.t + 1) }
    } else {
        // reach / hold: static target
        Sp = { t: S.t + 1, x: x_next, y: S.y, target: S.target }
    }
    const { O } = output({ P, S: Sp })
    return { Sp, O }
}

// machine vs simulated human (demo autopilot / sanity sims)
function step_sim({ P, S }) {
    const G = P._G || ensureGame(P)
    const g = M.gradHx(G, S.x, S.y)
    const x_next = M.clipvec(M.vsub(S.x, M.vscale(g, P.lr_sim || 0.05)), -1, 1)
    const y_next = machineStep({ P, G, x: x_next, y: S.y })
    const Sp = { t: S.t + 1, x: x_next, y: y_next }
    const { O } = output({ P, S: Sp })
    return { Sp, O }
}

function reset({ P }) {
    const PP = { ...P }
    PP.n = PP.n || 2
    PP.m = PP.m || 2
    const mode = PP.taskmode || 'game'
    const rand = M.rng((PP.seed || 1) + 7919 * (PP.trial_index || 0))

    let S
    if (mode === 'game') {
        const G = ensureGame(PP)
        // game-theoretic predictions, logged with params and drawn in debug
        const eq = M.equilibria(G)
        PP.eq = {
            NE: { x: eq.NE.x, y: eq.NE.y },
            SE: { x: eq.SE.x, y: eq.SE.y },
            CC: { x: eq.CC.x, y: eq.CC.y },
            MO: { x: eq.MO.x, y: eq.MO.y },
            K: eq.CC.K, L: eq.CC.L,
            steering: eq.ST.ok ? { L: eq.ST.L, l: eq.ST.l } : null,
        }
        if (PP.ynash == null) PP.ynash = eq.NE.y
        const x0 = PP.random
            ? M.zeros(PP.n).map(() => (rand() * 2 - 1) * 0.4)
            : (PP.x0 || M.zeros(PP.n))
        const y0 = PP.y0 || M.brM(G, x0)
        S = { t: 0, x: x0, y: y0 }
    } else {
        const target = mode === 'track'
            ? trackTarget(PP, 0)
            : (PP.target || M.zeros(PP.n).map(() => (rand() * 2 - 1) * 0.8))
        const x0 = PP.x0 || M.zeros(PP.n)
        S = { t: 0, x: x0, y: M.zeros(PP.m), target }
    }

    const I = { x: S.x.slice() }
    const { O } = output({ P: PP, S })
    return { P: PP, S, I, O }
}

export default { step, step_sim, reset }
